nodejs/require-in-the-middle

README.md, index.js, test/node_modules/internal/index.js, test/node_modules/internal/lib/a.js, test/node_modules/internal/lib/b.js, test/test.js
Thanks for the fantastic module!
Given that the purpose of this module is for monkeypatching, it would be useful to be able to monkeypatch module internals as well. This PR adds that by turning the first argument to `hook` into an options object that contains fields for both a list of modules, and a flag to enable calling the hook on module internals. Existing behavior should be preserved exactly.
Example: https://gist.github.com/kjin/cc7eb513fc389882afce978d9673e343
=> Add option to hook into module internals

index.js, test/test.js
Right now, if the `onrequire` hook returns a replacement value for a module (which I assume is allowable behavior), this replacement value won't get stored in the cache -- the original value will be stored instead. This means that requiring that module twice will give different results.
I changed this so that the replacement value gets cached instead, and added a test (which would fail without this change).
=> Make cache value replaceable

index.js, test/node_modules/mid-circular/bar.js, test/node_modules/mid-circular/foo.js, test/node_modules/mid-circular/index.js, test/test.js
This keeps track of in-progress patches so mid-circular dependencies don't result in the patch function being applied to the partial middle state, blocking the patching of the later completed state. Instead, only the outer state will be patched while inner states will skip patching because it seems there is already an in-progress patch.
cc @watson
=> Fix mid-circular dependencies

index.js, test/test.js
Previously, if the hook function was called more than once, only the callback given in the last call would be active. So if you either called the same hook function multiple times or if another module in your dependency tree had its own copy of the `require-in-the-middle` module, the last one to call `hook` would win.
With this change, the hooks will be called in series, where the last one to call the `hook` function will be the first to be called when a module is required (LIFO).
Fixes #11
=> fix: support calling hook function multiple times

package.json
This repo was moved to a different org recently, but the links in the package.json wasn't updated.
=> chore: update repo links in package.json

README.md
The old badge didn't show the correct dependency numbers, so let's just use a simpler one. As long as it links to the npm page then it's good 😄
=> chore: change npm badge in README.md

README.md, index.js, package.json, test/node_modules/sub-module/bar/index.js, test/node_modules/sub-module/conflict.js, test/node_modules/sub-module/conflict/index.js, test/node_modules/sub-module/foo.js, test/node_modules/sub-module/index.js, test/sub-module.js
This is required in order to support this use-case elastic/apm-agent-nodejs#913
~~Depends on #20~~
~~While creating this PR I added a lot of debug statements that I submitted as a separate PR: elastic/require-in-the-middle#20~~
~~I could make another PR without those changes, but thought it was good to have, so for now I've left them in.~~
=> feat: add support for sub-modules

index.js, test/test.js
BREAKING CHANGE: The API of the public `.cache` property changes.
=> perf: store the cache in a Map instead of an Object

index.js, package.json, test/test.js
This reverts commit 0bc8510a828f1787199d9cb96608e532083dc327.
The `module.builtinModules` wasn't included in early versions of Node.js 6 and 8 (pre v8.10.0 and pre v6.13.1). Since we want to retain support for those early versions, we'll revert this commit and reintroduce it in a major release
=> Revert "fix: support builtin core modules that contain slashes (#28)"

index.js, package.json, test/test.js
This was first introduced via #28, but was reverted again in #32 due to issues with early Node.js versions. This commit includes a fix for the issue introduced in #28.
=> fix: support builtin core modules that contain slashes

.github/workflows/test.yml, .gitignore, .npmrc, CHANGELOG.md, index.js, package.json, test/test.js
Since v16.0.0, v14.18.0 node has supported a 'node:'-prefix on
require() of core modules. They typically are an alias for unprefixed
builtin modules, e.g. 'http' and 'node:http' yield the same module.
However, new core modules may be added only with the prefix, e.g.
'node:test' added in node v18.0.0.
https://nodejs.org/api/modules.html#core-modules
This change adds support for a require-in-the-middle hook to capture
the node-prefixed aliases. I.e. `Hook(['http', ...], onRequire)` will
hook into `require('node:http')` and `require('http')`.
Refs: https://github.com/elastic/apm-agent-nodejs/issues/2816
----
@astorm Would you like to review this?  I'll get a draft PR for https://github.com/elastic/apm-agent-nodejs/issues/2816 as well that includes a test case of instrumenting …
=> feat: support 'node:'-prefixed core modules

CHANGELOG.md, index.js, test/already-monkey-patched-require.test.js
There might be an already monkey-patched 'require' that knows how to
resolve a special identifier. This is needed to use
require-in-the-middle with 'azure-functions-nodejs-worker', which
patches 'require' to support `require('@azure/functions-core')`.
=> feat: support deferring to the underlying 'require' implementation if Module._resolveFilename fails

.gitignore, CHANGELOG.md, index.js, test/require-cache-inval.js, test/test.js
This allows a user to delete from `require.cache` to trigger a re-load of a module (and a re-run of the hook's `onrequire`) on next `require()`.
This also removes the `.cache` field from the Hook object. It was never documented, but it wasn't prefixed with `_` to hint at being private. As well, some tests used it, which might have given the impression it could be used externally. I'm calling this a semver-major change to give a heads up to users that might have been using it.
Fixes: #61
=> feat!: use `require.cache` for caching patched exports for non-core modules

.gitignore, CHANGELOG.md, README.md, index.js, test/already-monkey-patched-require.test.js, test/babel/babel-register.js, test/legacy-default-export.js, test/require-cache-inval.js, test/sub-module.js, test/test.js
Also *prefer* this form. This is because it is, apparently, easier to
type for and use named exports with TypeScript and ESM, rather than
"default exports".
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/3701
=> feat: add named 'Hook' export

.github/workflows/test.yml, CHANGELOG.md, index.js, test/http2-is-builtin.js
For earlier versions of node -- before `Module.isBuiltin()` -- we use `require('resolve').isCore(name)` to determine if a module is built-in, a.k.a. is a "core" module. With https://github.com/elastic/require-in-the-middle/pull/63 an assert was added to the caching logic if there was a surprise -- a `core=false` module that isn't cached in `require.cache`.
This missed a case where this can happen: with the built-in 'http2' module in older versions of Node.js v8 when it was behind the `--expose-http2` flag.  The result would be a crash like this:
```
% node --expose-http2 http2-is-builtin.js
TAP version 13
assert.js:41
throw new errors.AssertionError({
^
AssertionError [ERR_ASSERTION]: unexpected that there is no Module entry for "http2" in require.cache
at ExportsCache.set …
```
=> fix: hooking "http2" with node 8.6 and "--expose-http2" would hit an assert

CHANGELOG.md, index.js, test/babel/babel-register.js
There can, in general, be something else in the process that is
manipulating `require.cache` -- e.g. `@babel/register` -- such that when
a module that RITM is hooking, it might *not* be in `require.cache`
after `require()`ing it.
Before this change, this would result in RITM crashing on an assert.
With this change RITM will fall back to caching the hooked module's exports
internally -- as it used to do in versions before v7 -- instead of
on the `require.cache[filename]` entry.
Fixes: https://github.com/elastic/require-in-the-middle/issues/72
=> fix: Don't crash if there are require.cache shenanigans in play

index.js
Makes the change proposed in #75.
Note that there are a few other early-returns of `exports` where we could in theory use the exports cache as well. However, those all occur prior to the call to `resolve.sync(...)`, which AFAICT is the slowest part of this code since that actually does a lot of filesystem operations. Everything before that point should be fast code that doesn't do any async filesystem/etc. operations, which means that the benefits to caching in that case is most likely negligible.
=> Cache exports in additional code paths

index.js, test/sub-module.js
Fix https://github.com/elastic/require-in-the-middle/issues/79
Fix the bug causing a hook used for both a module and some of its sub module to only hook into the parent module. 
```js
new Hook(['sub-module/foo', 'sub-module'], handler)
```
=> Fix hooking parent and sub module with a single hook

Makefile
npm v10 behaviour for 'npm view example@1.2.3 version' when that
version does not exist has changed. It now exits non-zero and
emits error info to stdout.
=> chore: fix 'make cutarelease' to work with more recent npm

index.js, test/mapped-exports.js, test/node_modules/mapped-exports/dist/cjs/bar.cjs, test/node_modules/mapped-exports/dist/esm/bar.js, test/node_modules/mapped-exports/foo.cjs, test/node_modules/mapped-exports/foo.js, test/node_modules/mapped-exports/index.js, test/node_modules/mapped-exports/package.json
This PR fixes an issue with mapped exports. Basically, if a module exports multiple versions of the same source then the commonjs export will end up with a file extension added. When the file extension is added, it breaks the allow list lookup and results in the hook never being applied.
=> Handle mapped exports

index.js
This is a copy of #25 which looks like it was opened before CI tests were added.
I've fixed the original PR to pass on all tested versions.
If we made the minimum supported Node version `>= v8.10.0 | >= v9.3.0` then we could remove `resolve` as a dependency entirely but this would be a breaking change!
=> refactor: use core Node.js resolve function if possible

LICENSE
Looking at the other repos under the `nodejs` org, it seems that this is the strategy for copyright. But I might be mistaken
=> chore: update copyright going forward

CHANGELOG.md, README.md, package.json, test/require-cache-inval.js
The GitHub repo was just moved from the `elastic` to the `nodejs` org on GitHub. For details, see: https://github.com/nodejs/admin/issues/890
=> chore: update GitHub URLs to point to Node.js org

index.js
Fixes #105 by adding a check for `require.resolve` before trying to access `require.resolve.paths`.
=> fix: Runtime exception in Node SEA mode
